=== resmoio/custom-schema-examples/schema.json
{
	"type": "object",
	"resmo": {
		"id": "employeeId",
		"name": "$.employee.username",
		"importantFields": [
			"employeeId",
			"employee",
			"active"
		]
	},
	"title": "Employee Schema",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"properties": {
		"active": {
			"type": "boolean",
			"default": false
		},
		"salary": {
			"type": "number",
			"default": 0
		},
		"manager": {
			"type": "string",
			"default": ""
		},
		"employee": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"default": ""
				},
				"email": {
					"type": "string",
					"default": ""
				},
				"username": {
					"type": "string",
					"default": ""
				}
			}
		},
		"createdAt": {
			"type": "string",
			"default": ""
		},
		"department": {
			"type": "string",
			"default": ""
		},
		"employeeId": {
			"type": "string",
			"title": "The employeeId Schema",
			"examples": [
				"18129"
			]
		}
	}
}

=== resmoio/custom-schema-examples/bulk-payload.json
[
    {
        "employeeId": "18129",
        "employee": {
            "name": "lorem ipsum",
            "username": "lipsum",
            "email": "lipsum@resmo.com"
        },
        "createdAt": "2021-11-20",
        "department": "Integrations",
        "salary": 1230.0,
        "manager": "dolor",
        "active": true
      },
      {
        "employeeId": "89848",
        "employee": {
            "name": "dolor",
            "username": "dolor",
            "email": "dolor@resmo.com"
        },
        "createdAt": "2019-09-12",
        "department": "Management",
        "salary": 2100.0,
        "manager": "",
        "active": true
      },
      {
        "employeeId": "16548",
        "employee": {
            "name": "sit amet",
            "username": "samet",
            "email": "samet@resmo.com"
        },
        "createdAt": "2022-05-17",
        "department": "IT",
        "salary": 1000.0,
        "manager": "lipsum",
        "active": false
      }
]

=== resmoio/custom-schema-examples/bulk-payload-v2.json
[
    {
        "employeeId": "18129",
        "employee": {
            "name": "lorem ipsum",
            "username": "lipsum",
            "email": "lipsum@resmo.com"
        },
        "createdAt": "2021-11-20",
        "department": "Integrations",
        "salary": 1260.0,
        "manager": "dolor",
        "active": true
      },
      {
        "employeeId": "89848",
        "employee": {
            "name": "new dolor",
            "username": "dolor",
            "email": "dolor@resmo.com"
        },
        "createdAt": "2019-09-12",
        "department": "Management",
        "salary": 2100.0,
        "manager": "",
        "active": true
      },
      {
        "employeeId": "72732",
        "employee": {
            "name": "new employee",
            "username": "new",
            "email": "new@resmo.com"
        },
        "createdAt": "2022-12-14",
        "department": "Integrations",
        "salary": 0.0,
        "manager": "cem",
        "active": true
      }
]
